### ISSUE TITLE
Not response from swellrt server in some cases

### ISSUE THREAD

**Issue by MercusChan** [SwellRT/swellrt#230]
During development, in some cases, swellrt server is very busy. I need to restart the docker container to solve.

In fact, I don't know how to repeat, but I had collected the thread dump before restart the docker container.

Anyway to avoid not response?

[thread_dump_1.txt](https://github.com/P2Pvalue/swellrt/files/1634550/thread_dump_1.txt)
[thread_dump_2.txt](https://github.com/P2Pvalue/swellrt/files/1634551/thread_dump_2.txt)

**Comment by pablojan** [comment]
See https://github.com/SwellRT/swellrt/issues/243 
Major issues are solved in [ 2.0.x-beta versions](https://github.com/SwellRT/swellrt/releases)
